export const SET_NETWORK_ELEMENTS_LIST = 'SET_NETWORK_ELEMENTS_LIST';
export const SET_NETWORK_ELEMENTS_FILTERED_LIST = 'SET_NETWORK_ELEMENTS_FILTERED_LIST';
export const SET_SELECTED_NETWORK_ELEMENTS = 'SET_SELECTED_NETWORK_ELEMENTS';
export const SET_UNSELECT_ALL_NETWORK_ELEMENTS = 'SET_UNSELECT_ALL_NETWORK_ELEMENTS';
export const SET_SELECT_ALL_NETWORK_ELEMENTS = 'SET_SELECT_ALL_NETWORK_ELEMENTS';
